In [13]:
import pandas as pd

df = pd.read_excel('Areas-of-interest-POIs\\sample_1000.xlsx')
df.head()

,mid_label,mid_label_new,bosserhof_class_clean,bosserhof_class_clean.1,osm_names,gml_id,target_taz,volume_m3,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,"['Leisure', 'Workers']",NaN,restaurants gastronomy,NaN,['Enoteca Vetrone'],236928,Rühen 7_472,1554.252341,NaN,NaN,NaN,NaN
1,['Workers'],NaN,normal office,NaN,NaN,535772,WOB Ehmen 2_289,453.347111,NaN,NaN,NaN,NaN
2,['Workers'],NaN,industrial operations production,NaN,NaN,477334,Gifhorn 04_416,727.942206,NaN,NaN,NaN,NaN
3,"['Retail_Daily', 'Workers', 'Retail_Non-Daily']","['Workers', 'Retail_Non-Daily']",retail small scale,NaN,"[""Deutsche Bank;Ernsting's family""]",388629,Goslar 18_565,17437.047953,NaN,NaN,NaN,NaN
4,['Workers'],NaN,normal office,NaN,NaN,81399,Bad Harzburg Schlewecke_518,248.752010,NaN,NaN,NaN,NaN

In [14]:
import geopandas as gpd

df1 = gpd.read_file('Areas-of-interest-POIs\\building_level_redistributed_values_with_fallback.gpkg')
df1.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,potentials,bosserhof_class_clean,building_index,target_taz,assigned_Kindergarten,assigned_Leisure,assigned_Retail_Daily,assigned_Retail_Non-Daily,assigned_School,assigned_University,assigned_Workers,geometry
0,13,89.209230,None,normal office,['Workers'],258.71,normal office,0,BS Hondelage 1_192,0.0,0.0,0.0,0.0,0.0,0.0,0.134531,MULTIPOLYGON Z (((608781.076 5797034.372 86.80...
1,14,119.566130,None,normal office,['Workers'],346.74,normal office,1,BS Hondelage 1_192,0.0,0.0,0.0,0.0,0.0,0.0,0.180308,"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,..."
2,15,1033.650498,None,normal office,['Workers'],2997.59,normal office,2,BS Hondelage 1_192,0.0,0.0,0.0,0.0,0.0,0.0,1.558773,MULTIPOLYGON Z (((609428.62 5797079.031 79.962...
3,16,46.560366,None,normal office,['Workers'],135.03,normal office,3,BS Hondelage 1_192,0.0,0.0,0.0,0.0,0.0,0.0,0.070217,"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."
4,0,931.423451,None,normal office,['Workers'],2701.13,normal office,4,BS Hondelage 1_192,0.0,0.0,0.0,0.0,0.0,0.0,1.404611,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...

In [15]:
df["gml_id"] = df["gml_id"].astype(str)
df1["gml_id"] = df1["gml_id"].astype(str)

merged_df = df.merge(
    df1,
    on="gml_id",
    how="left",
    suffixes=("_sample", "_full")
)

In [16]:
merged_df.head()

,mid_label_sample,mid_label_new,bosserhof_class_clean_sample,bosserhof_class_clean.1,osm_names_sample,gml_id,target_taz_sample,volume_m3_sample,Unnamed: 8,Unnamed: 9,...,building_index,target_taz_full,assigned_Kindergarten,assigned_Leisure,assigned_Retail_Daily,assigned_Retail_Non-Daily,assigned_School,assigned_University,assigned_Workers,geometry
0,"['Leisure', 'Workers']",NaN,restaurants gastronomy,NaN,['Enoteca Vetrone'],236928,Rühen 7_472,1554.252341,NaN,NaN,...,112402,Rühen 7_472,0.0,73.608154,0.000000,0.00000,0.0,0.0,0.763497,MULTIPOLYGON Z (((627916.268 5817111.097 67.36...
1,['Workers'],NaN,normal office,NaN,NaN,535772,WOB Ehmen 2_289,453.347111,NaN,NaN,...,249322,WOB Ehmen 2_289,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.901841,MULTIPOLYGON Z (((616524.144 5805637.301 90.17...
2,['Workers'],NaN,industrial operations production,NaN,NaN,477334,Gifhorn 04_416,727.942206,NaN,NaN,...,188712,Gifhorn 04_416,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.778347,MULTIPOLYGON Z (((604990.302 5815446.517 57.42...
3,"['Retail_Daily', 'Workers', 'Retail_Non-Daily']","['Workers', 'Retail_Non-Daily']",retail small scale,NaN,"[""Deutsche Bank;Ernsting's family""]",388629,Goslar 18_565,17437.047953,NaN,NaN,...,148200,Goslar 18_565,0.0,0.000000,240.611421,483.23737,0.0,0.0,10.168546,MULTIPOLYGON Z (((598148.597 5751933.146 262.0...
4,['Workers'],NaN,normal office,NaN,NaN,81399,Bad Harzburg Schlewecke_518,248.752010,NaN,NaN,...,41566,Bad Harzburg Schlewecke_518,0.0,0.000000,0.000000,0.00000,0.0,0.0,0.055343,MULTIPOLYGON Z (((606504.915 5751036.235 226.5...

In [17]:
merged_df.columns

Index(['mid_label_sample', 'mid_label_new', 'bosserhof_class_clean_sample',
       'bosserhof_class_clean.1', 'osm_names_sample', 'gml_id',
       'target_taz_sample', 'volume_m3_sample', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'volume_m3_full', 'osm_names_full',
       'bosserhof_class', 'mid_label_full', 'potentials',
       'bosserhof_class_clean_full', 'building_index', 'target_taz_full',
       'assigned_Kindergarten', 'assigned_Leisure', 'assigned_Retail_Daily',
       'assigned_Retail_Non-Daily', 'assigned_School', 'assigned_University',
       'assigned_Workers', 'geometry'],
      dtype='object')

In [18]:
merged_df = merged_df[['mid_label_sample', 'mid_label_new', 'bosserhof_class_clean_sample',
       'bosserhof_class_clean.1', 'osm_names_sample', 'gml_id','volume_m3_sample', 'geometry']]

In [19]:
merged_df.head()

,mid_label_sample,mid_label_new,bosserhof_class_clean_sample,bosserhof_class_clean.1,osm_names_sample,gml_id,volume_m3_sample,geometry
0,"['Leisure', 'Workers']",NaN,restaurants gastronomy,NaN,['Enoteca Vetrone'],236928,1554.252341,MULTIPOLYGON Z (((627916.268 5817111.097 67.36...
1,['Workers'],NaN,normal office,NaN,NaN,535772,453.347111,MULTIPOLYGON Z (((616524.144 5805637.301 90.17...
2,['Workers'],NaN,industrial operations production,NaN,NaN,477334,727.942206,MULTIPOLYGON Z (((604990.302 5815446.517 57.42...
3,"['Retail_Daily', 'Workers', 'Retail_Non-Daily']","['Workers', 'Retail_Non-Daily']",retail small scale,NaN,"[""Deutsche Bank;Ernsting's family""]",388629,17437.047953,MULTIPOLYGON Z (((598148.597 5751933.146 262.0...
4,['Workers'],NaN,normal office,NaN,NaN,81399,248.752010,MULTIPOLYGON Z (((606504.915 5751036.235 226.5...

In [22]:
print('geometry' in merged_df.columns)

True

In [25]:
merged_gdf = gpd.GeoDataFrame(
    merged_df,
    geometry='geometry',
    crs=df1.crs
)

merged_gdf.to_file(
    'Areas-of-interest-POIs\\validation_merged.gpkg',
    driver='GPKG'
)

In [26]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   mid_label_sample              1000 non-null   object
 1   mid_label_new                 56 non-null     object
 2   bosserhof_class_clean_sample  1000 non-null   object
 3   bosserhof_class_clean.1       33 non-null     object
 4   osm_names_sample              228 non-null    object
 5   gml_id                        1000 non-null   object
 6   volume_m3_sample              1000 non-null   float64
 7   geometry                      1000 non-null   geometry
dtypes: float64(1), geometry(1), object(6)
memory usage: 62.6+ KB