In [1]:
import geopandas as gpd

gdf = gpd.read_file(r"Areas-of-interest-POIs\bs_area_correct.gpkg", layer="regionbsstructuredata_zone")
gdf.head()

,NO,CODE,NAME,TYPENO,RO_LANDK~1,SG_0_EW_~2,SG_1_EW_~3,SG_1_STU~4,SG_2_EWT~5,SG_2_EWT~6,...,SG_6_BE~20,SG_6_BE~21,SG_6_FR~22,SG_6_FR~23,SG_6_FR~24,SG_6_GE~25,SG_6_PR~26,SG_6_SONST,SG_7_AN~27,geometry
0,310101901,None,BS Stadtkern 6,1,Braunschweig,3040,623.50,40.66,106.42,270.12,...,9.0,0.0,176.0,1166.0,990.0,8.0,17.0,0.0,0.0,"MULTIPOLYGON (((603845.77 5791532.411, 603828...."
1,310101902,None,BS Stadtkern 9,1,Braunschweig,2352,175.74,25.38,31.27,79.38,...,11.0,0.0,22.0,772.0,750.0,8.0,7.0,1.0,0.0,"MULTIPOLYGON (((603798.46 5791316.225, 603740...."
2,310101903,None,BS Stadtkern 13,1,Braunschweig,3698,1321.42,109.87,226.38,574.60,...,2.0,0.0,105.0,611.0,506.0,9.0,12.0,0.0,0.0,"MULTIPOLYGON (((603829.121 5790964.967, 603769..."
3,310101904,None,BS Stadtkern 17,1,Braunschweig,2635,148.38,14.42,27.99,71.06,...,1.0,0.0,5.0,745.0,740.0,3.0,1.0,0.0,0.0,"MULTIPOLYGON (((603455.156 5791018.867, 603492..."
4,310101905,None,BS Stadtkern 15,1,Braunschweig,2031,370.40,37.21,67.53,171.40,...,8.0,0.0,17.0,587.0,570.0,9.0,6.0,1.0,0.0,"MULTIPOLYGON (((603968.386 5791312.927, 603981..."

In [2]:
import fiona

layers = fiona.listlayers(r"C:\Users\Mayur Patel\bs_area_correct.gpkg")
print(layers)

['v10_2025_zone', 'regionbsstructuredata_zone']

In [3]:
print(gdf.columns)

Index(['NO', 'CODE', 'NAME', 'TYPENO', 'RO_LANDK~1', 'SG_0_EW_~2',
       'SG_1_EW_~3', 'SG_1_STU~4', 'SG_2_EWT~5', 'SG_2_EWT~6', 'SG_2_EWT~7',
       'SG_3_BES~8', 'SG_3_BES~9', 'SG_3_BE~10', 'SG_3_BE~11', 'SG_3_BE~12',
       'SG_3_BE~13', 'SG_3_BE~14', 'SG_3_BE~15', 'SG_3_BE~16', 'SG_3_BE~17',
       'SG_4_BS', 'SG_4_GSCH', 'SG_4_HS', 'SG_4_KITA', 'SG_4_WFSCH',
       'SG_5_EK~18', 'SG_5_EK~19', 'SG_5_EK_TB', 'SG_6_BE~20', 'SG_6_BE~21',
       'SG_6_FR~22', 'SG_6_FR~23', 'SG_6_FR~24', 'SG_6_GE~25', 'SG_6_PR~26',
       'SG_6_SONST', 'SG_7_AN~27', 'geometry'],
      dtype='object')

In [4]:
gdf.columns[20:29]

Index(['SG_3_BE~17', 'SG_4_BS', 'SG_4_GSCH', 'SG_4_HS', 'SG_4_KITA',
       'SG_4_WFSCH', 'SG_5_EK~18', 'SG_5_EK~19', 'SG_5_EK_TB'],
      dtype='object')

In [5]:
gdf.columns[32]

'SG_6_FR~23'

In [6]:
gdf['Education_School'] = gdf['SG_4_BS'] + gdf['SG_4_GSCH'] + gdf['SG_4_WFSCH']

gdf = gdf.rename(columns={
    'SG_3_BE~17': 'Workers',
    'SG_4_HS': 'University_Students',
    'SG_4_KITA': 'Kindergarten',
    'SG_5_EK~18': 'Shopping_Total',
    'SG_5_EK~19': 'Shopping_NonEssential',
    'SG_5_EK_TB': 'Shopping_DailyNeeds',
    'SG_6_FR~23': 'Leisure'
})

columns_to_keep = [
    'NAME',
    'Workers',
    'Education_School',
    'University_Students',
    'Kindergarten',
    'Shopping_Total',
    'Shopping_NonEssential',
    'Shopping_DailyNeeds',
    'Leisure',
    'geometry'
]

gdf = gdf[columns_to_keep]

gdf.head()

,NAME,Workers,Education_School,University_Students,Kindergarten,Shopping_Total,Shopping_NonEssential,Shopping_DailyNeeds,Leisure,geometry
0,BS Stadtkern 6,2416.29,0.0,0.0,0,9970.0,8757,1213,1166.0,"MULTIPOLYGON (((603845.77 5791532.411, 603828...."
1,BS Stadtkern 9,2176.16,934.0,0.0,0,26243.0,22039,4204,772.0,"MULTIPOLYGON (((603798.46 5791316.225, 603740...."
2,BS Stadtkern 13,2376.94,428.0,0.0,68,11627.0,11263,364,611.0,"MULTIPOLYGON (((603829.121 5790964.967, 603769..."
3,BS Stadtkern 17,2486.83,0.0,0.0,0,896.0,172,724,745.0,"MULTIPOLYGON (((603455.156 5791018.867, 603492..."
4,BS Stadtkern 15,1660.61,0.0,0.0,0,21637.0,10208,11429,587.0,"MULTIPOLYGON (((603968.386 5791312.927, 603981..."

In [7]:
print(gdf.columns)

Index(['NAME', 'Workers', 'Education_School', 'University_Students',
       'Kindergarten', 'Shopping_Total', 'Shopping_NonEssential',
       'Shopping_DailyNeeds', 'Leisure', 'geometry'],
      dtype='object')

In [8]:
df = gpd.read_file(r"Areas-of-interest-POIs\final_potentials_calculation.gpkg")
df.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,potentials,geometry
0,13,89.209230,None,normal office,['work'],258.71,MULTIPOLYGON Z (((608781.076 5797034.372 86.80...
1,14,119.566130,None,normal office,['work'],346.74,"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,..."
2,15,1033.650498,None,normal office,['work'],2997.59,MULTIPOLYGON Z (((609428.62 5797079.031 79.962...
3,16,46.560366,None,normal office,['work'],135.03,"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."
4,0,931.423451,None,normal office,['work'],2701.13,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...

In [9]:
df['mid_label'].value_counts()

mid_label
['work']                                    218112
['work' 'errands']                            8204
['work' 'business']                           6795
['leisure']                                   4713
['errands' 'work']                            2552
                                             ...
['business' 'leisure']                           1
['leisure' 'business' 'meetup' 'work']           1
['errands' 'leisure' 'meetup']                   1
['work' 'childcare' 'sports']                    1
['leisure' 'errands' 'retail_non_daily']         1
Name: count, Length: 369, dtype: int64

In [10]:
import re
import pandas as pd
import numpy as np

valid_labels = [
    "Workers",
    "University",
    "School",
    "Kindergarten",
    "Retail_Daily",
    "Retail_Non-Daily",
    "Leisure",
]

label_map = {
    "work": "Workers",
    "business": "Workers",
    "university": "University",
    "school": "School",
    "childcare": "Kindergarten",
    "retail_daily": "Retail_Daily",
    "retail_non_daily": "Retail_Non-Daily",
    "errands": "Retail_Daily", # errands can be considered daily retail, but this is not true in all cases (public offices, banks, etc. need to decide about this)
    "leisure": "Leisure",
    "sports": "Leisure",
    "meetup": "Leisure",
    "lessons": "Leisure",
}

pattern = re.compile("|".join(sorted(map(re.escape, label_map.keys()), key=len, reverse=True)))


def clean_mid_label(x):
    if x is None:
        return []

    if isinstance(x, float) and pd.isna(x):
        return []

    if isinstance(x, (list, tuple, set, np.ndarray)):
        raw_labels = [str(v).strip() for v in x]
    else:
        raw_labels = pattern.findall(str(x))

    mapped = [label_map[label] for label in raw_labels if label in label_map]

    # remove duplicates, keep order
    return list(dict.fromkeys(mapped))


df["mid_label"] = df["mid_label"].apply(clean_mid_label)

In [11]:
df.head()

,gml_id,volume_m3,osm_names,bosserhof_class,mid_label,potentials,geometry
0,13,89.209230,None,normal office,[Workers],258.71,MULTIPOLYGON Z (((608781.076 5797034.372 86.80...
1,14,119.566130,None,normal office,[Workers],346.74,"MULTIPOLYGON Z (((609122.06 5797462.983 85.46,..."
2,15,1033.650498,None,normal office,[Workers],2997.59,MULTIPOLYGON Z (((609428.62 5797079.031 79.962...
3,16,46.560366,None,normal office,[Workers],135.03,"MULTIPOLYGON Z (((609661.688 5797071.969 77.4,..."
4,0,931.423451,None,normal office,[Workers],2701.13,MULTIPOLYGON Z (((609554.181 5797264.172 78.94...

In [12]:
df['mid_label'].value_counts()

mid_label
[Workers]                                                         225117
[Workers, Retail_Daily]                                             8732
[Leisure]                                                           7452
[Retail_Daily, Workers]                                             4085
[Leisure, Workers]                                                  3637
                                                                   ...
[Retail_Daily, Kindergarten, Retail_Non-Daily, Workers]                1
[Retail_Daily, Retail_Non-Daily, University, Leisure, Workers]         1
[Retail_Daily, Kindergarten, Workers]                                  1
[Kindergarten, Retail_Daily, Leisure, Workers]                         1
[Retail_Daily, Leisure, Kindergarten, Workers]                         1
Name: count, Length: 100, dtype: int64

In [13]:
df.to_file(r"Areas-of-interest-POIs\final_potentials_calculation_test.gpkg", driver="GPKG")

In [14]:
gdf.columns

Index(['NAME', 'Workers', 'Education_School', 'University_Students',
       'Kindergarten', 'Shopping_Total', 'Shopping_NonEssential',
       'Shopping_DailyNeeds', 'Leisure', 'geometry'],
      dtype='object')

In [15]:
gdf = gdf.rename(columns={"NAME": "Region_Name", "Education_School": "School", "University_Students": "University", "Shopping_NonEssential": "Retail_Non-Daily", "Shopping_DailyNeeds": "Retail_Daily"})
gdf.head()

,Region_Name,Workers,School,University,Kindergarten,Shopping_Total,Retail_Non-Daily,Retail_Daily,Leisure,geometry
0,BS Stadtkern 6,2416.29,0.0,0.0,0,9970.0,8757,1213,1166.0,"MULTIPOLYGON (((603845.77 5791532.411, 603828...."
1,BS Stadtkern 9,2176.16,934.0,0.0,0,26243.0,22039,4204,772.0,"MULTIPOLYGON (((603798.46 5791316.225, 603740...."
2,BS Stadtkern 13,2376.94,428.0,0.0,68,11627.0,11263,364,611.0,"MULTIPOLYGON (((603829.121 5790964.967, 603769..."
3,BS Stadtkern 17,2486.83,0.0,0.0,0,896.0,172,724,745.0,"MULTIPOLYGON (((603455.156 5791018.867, 603492..."
4,BS Stadtkern 15,1660.61,0.0,0.0,0,21637.0,10208,11429,587.0,"MULTIPOLYGON (((603968.386 5791312.927, 603981..."

In [16]:
gdf.to_file(r"Areas-of-interest-POIs\bs_area_corrected-updated.gpkg", driver="GPKG")

In [17]:
gdf = gdf.reset_index(drop=True).copy()

gdf["taz_uid"] = (
    gdf["Region_Name"].astype(str)
    + "_"
    + gdf.index.astype(str)
)

In [18]:
# ============================================================
# IMPORTS
# ============================================================

import ast
import numpy as np
import pandas as pd
import geopandas as gpd


# ============================================================
# CONFIG
# ============================================================

TAZ_ID_COL = "taz_uid"

CATEGORY_COLS = [
    "Workers",
    "School",
    "University",
    "Kindergarten",
    "Retail_Daily",
    "Retail_Non-Daily",
    "Leisure",
]

WORKER_COL = "Workers"

CATEGORY_TO_LABEL = {
    "Workers": "Workers",
    "School": "School",
    "University": "University",
    "Kindergarten": "Kindergarten",
    "Retail_Daily": "Retail_Daily",
    "Retail_Non-Daily": "Retail_Non-Daily",
    "Leisure": "Leisure",
}

# ============================================================
# WORKER CAP CONFIG
# ============================================================

STRICT_WORKER_CAP_CLASSES = [
    "restaurants gastronomy",
    "retail small scale",
    "fitness wellness",
    "entertainment culture",
    "large cinemas",
    "large discos fun leisure pools",
    "arenas large events",
    "theme parks",
    "car dealerships",
    "customer service",
    "vehicle electrical repair",
]

LARGE_FORMAT_RETAIL_CAP_CLASSES = [
    "shopping centers",
    "department stores",
    "self service department stores",
    "discount stores",
    "hypermarkets superstores",
    "diy stores",
    "furniture stores",
    "factory outlet centers",
]

# Change these values if needed
STRICT_CAP_QUANTILE = 0.75
LARGE_FORMAT_CAP_QUANTILE = 0.95

OUTPUT_GPKG = "Areas-of-interest-POIs/building_level_redistributed_values_with_fallback.gpkg"
VALIDATION_CSV = "Areas-of-interest-POIs/redistribution_validation_with_fallback.csv"
ALLOCATION_LOG_CSV = "Areas-of-interest-POIs/redistribution_allocation_log.csv"


# ============================================================
# HELPER: PARSE mid_label
# ============================================================

def parse_labels(x):
    if isinstance(x, list):
        return x

    if isinstance(x, np.ndarray):
        return list(x)

    if pd.isna(x):
        return []

    if isinstance(x, str):
        x = x.strip()

        if x in ["", "None", "nan", "NaN", "[]"]:
            return []

        try:
            parsed = ast.literal_eval(x)
            if isinstance(parsed, list):
                return parsed
        except Exception:
            pass

        x = x.strip("[]")
        return [
            v.strip().strip("'").strip('"')
            for v in x.split(",")
            if v.strip()
        ]

    return []


# ============================================================
# HELPER: CLEAN BOSSERHOF CLASS
# ============================================================

def clean_bosserhof_class(x):
    if pd.isna(x):
        return ""

    return (
        str(x)
        .lower()
        .strip()
        .replace("-", " ")
        .replace("_", " ")
        .replace("  ", " ")
    )


# ============================================================
# 1. PREPARE DATA
# ============================================================

taz = gdf.copy()
buildings = df.copy()

if not isinstance(taz, gpd.GeoDataFrame):
    taz = gpd.GeoDataFrame(taz, geometry="geometry")

if not isinstance(buildings, gpd.GeoDataFrame):
    buildings = gpd.GeoDataFrame(buildings, geometry="geometry", crs=taz.crs)

if buildings.crs != taz.crs:
    buildings = buildings.to_crs(taz.crs)

taz = taz[[TAZ_ID_COL, "geometry"] + CATEGORY_COLS].copy()
buildings = buildings.copy()

buildings["mid_label"] = buildings["mid_label"].apply(parse_labels)
buildings["volume_m3"] = pd.to_numeric(buildings["volume_m3"], errors="coerce").fillna(0)
buildings["potentials"] = pd.to_numeric(buildings["potentials"], errors="coerce").fillna(0)

buildings["bosserhof_class_clean"] = buildings["bosserhof_class"].apply(clean_bosserhof_class)

buildings = buildings.reset_index(drop=True)
buildings["building_index"] = buildings.index


# ============================================================
# 1A. CREATE DATA-DRIVEN WORKER VOLUME CAPS
# ============================================================

valid_cap_data = buildings[
    (buildings["volume_m3"] > 0) &
    (buildings["bosserhof_class_clean"] != "")
].copy()

STRICT_CLASS_VOLUME_CAPS = (
    valid_cap_data[
        valid_cap_data["bosserhof_class_clean"].isin(STRICT_WORKER_CAP_CLASSES)
    ]
    .groupby("bosserhof_class_clean")["volume_m3"]
    .quantile(STRICT_CAP_QUANTILE)
    .to_dict()
)

LARGE_FORMAT_CLASS_VOLUME_CAPS = (
    valid_cap_data[
        valid_cap_data["bosserhof_class_clean"].isin(LARGE_FORMAT_RETAIL_CAP_CLASSES)
    ]
    .groupby("bosserhof_class_clean")["volume_m3"]
    .quantile(LARGE_FORMAT_CAP_QUANTILE)
    .to_dict()
)

print("\nStrict worker caps:")
for k, v in STRICT_CLASS_VOLUME_CAPS.items():
    print(f"{k}: {v:.2f} m³")

print("\nLarge-format retail worker caps:")
for k, v in LARGE_FORMAT_CLASS_VOLUME_CAPS.items():
    print(f"{k}: {v:.2f} m³")


# ============================================================
# HELPER: WORKER EFFECTIVE WEIGHT
# ============================================================

def get_worker_effective_weight(row):
    """
    Only affects Workers.

    Strict classes:
        use class-specific 75th percentile volume cap

    Large-format retail classes:
        use class-specific 95th percentile volume cap

    Other classes:
        use original potentials unchanged
    """

    cls = row.get("bosserhof_class_clean", "")
    volume = row.get("volume_m3", 0)
    potentials = row.get("potentials", 0)

    if pd.isna(volume) or pd.isna(potentials):
        return 0

    if volume <= 0 or potentials <= 0:
        return 0

    if cls in STRICT_CLASS_VOLUME_CAPS:
        cap = STRICT_CLASS_VOLUME_CAPS[cls]
        effective_volume = min(volume, cap)
        return potentials * (effective_volume / volume)

    if cls in LARGE_FORMAT_CLASS_VOLUME_CAPS:
        cap = LARGE_FORMAT_CLASS_VOLUME_CAPS[cls]
        effective_volume = min(volume, cap)
        return potentials * (effective_volume / volume)

    return potentials


def get_worker_weight_method(row):
    cls = row.get("bosserhof_class_clean", "")

    if cls in STRICT_CLASS_VOLUME_CAPS:
        return "worker_strict_class_volume_capped_p75"

    if cls in LARGE_FORMAT_CLASS_VOLUME_CAPS:
        return "worker_large_format_volume_capped_p95"

    return "worker_potentials_original"


# ============================================================
# 2. ASSIGN BUILDINGS TO TAZ
# ============================================================

intersection = gpd.overlay(
    buildings,
    taz[[TAZ_ID_COL, "geometry"]],
    how="intersection"
)

intersection["intersect_area"] = intersection.geometry.area

intersection_sorted = intersection.sort_values(
    "intersect_area",
    ascending=False
)

best_match = intersection_sorted.drop_duplicates(
    subset=["building_index"]
)

buildings_taz = buildings.merge(
    best_match[["building_index", TAZ_ID_COL]],
    on="building_index",
    how="left"
)

buildings_taz = buildings_taz.rename(columns={TAZ_ID_COL: "target_taz"})


# ============================================================
# 3. CREATE BUILDING-ACTIVITY CANDIDATE TABLE
# ============================================================

candidate_rows = []

for _, row in buildings_taz.iterrows():
    labels = row["mid_label"]

    non_worker_labels = [
        lab for lab in labels
        if lab != CATEGORY_TO_LABEL[WORKER_COL]
    ]

    n_non_worker = len(non_worker_labels)

    for category, label in CATEGORY_TO_LABEL.items():

        if label not in labels:
            continue

        if category == WORKER_COL:
            weight = get_worker_effective_weight(row)
            weight_method = get_worker_weight_method(row)

        else:
            if n_non_worker == 0:
                continue

            weight = row["volume_m3"] / n_non_worker
            weight_method = "volume_split_by_non_worker_labels"

        if pd.isna(weight) or weight <= 0:
            continue

        candidate_rows.append({
            "building_index": row["building_index"],
            "gml_id": row.get("gml_id", None),
            "target_taz": row["target_taz"],
            "category": category,
            "weight": weight,
            "weight_method": weight_method,
            "volume_m3": row["volume_m3"],
            "potentials": row["potentials"],
            "bosserhof_class": row.get("bosserhof_class", None),
            "bosserhof_class_clean": row.get("bosserhof_class_clean", None),
        })

candidates = pd.DataFrame(candidate_rows)

print("\nCandidate activity rows:", len(candidates))

print("\nWorker candidate weight methods:")
print(
    candidates[candidates["category"] == WORKER_COL]["weight_method"]
    .value_counts(dropna=False)
)


# ============================================================
# 4. BUILD TAZ NEIGHBOR TABLE
# ============================================================

taz_for_neighbors = taz[[TAZ_ID_COL, "geometry"]].copy().reset_index(drop=True)

neighbors = gpd.sjoin(
    taz_for_neighbors,
    taz_for_neighbors,
    how="left",
    predicate="touches"
)

neighbors = neighbors[
    neighbors[f"{TAZ_ID_COL}_left"] != neighbors[f"{TAZ_ID_COL}_right"]
].copy()

neighbor_dict = (
    neighbors
    .groupby(f"{TAZ_ID_COL}_left")[f"{TAZ_ID_COL}_right"]
    .apply(list)
    .to_dict()
)


# ============================================================
# 5. REDISTRIBUTION WITH FALLBACK
# ============================================================

LOCAL_POOL_CATEGORIES = [
    "School",
    "University",
    "Kindergarten",
]

allocation_parts = []

for _, source_row in taz.iterrows():

    source_taz = source_row[TAZ_ID_COL]
    neighbor_tazs = neighbor_dict.get(source_taz, [])

    for category in CATEGORY_COLS:

        source_total = pd.to_numeric(source_row[category], errors="coerce")

        if pd.isna(source_total) or source_total == 0:
            continue

        if category in LOCAL_POOL_CATEGORIES:

            local_tazs = [source_taz] + neighbor_tazs

            selected = candidates[
                (candidates["category"] == category) &
                (candidates["target_taz"].isin(local_tazs))
            ].copy()

            assignment_level = "local_pool_same_plus_neighbor"

            if selected.empty:
                selected = candidates[
                    candidates["category"] == category
                ].copy()

                assignment_level = "global_fallback"

        else:

            selected = candidates[
                (candidates["category"] == category) &
                (candidates["target_taz"] == source_taz)
            ].copy()

            assignment_level = "within_taz"

            if selected.empty and len(neighbor_tazs) > 0:
                selected = candidates[
                    (candidates["category"] == category) &
                    (candidates["target_taz"].isin(neighbor_tazs))
                ].copy()

                assignment_level = "neighbor_taz"

            if selected.empty:
                selected = candidates[
                    candidates["category"] == category
                ].copy()

                assignment_level = "global_fallback"

        if selected.empty:
            allocation_parts.append(pd.DataFrame([{
                "source_taz": source_taz,
                "target_taz": None,
                "building_index": None,
                "gml_id": None,
                "category": category,
                "source_total": source_total,
                "weight": 0,
                "weight_sum": 0,
                "assigned_value": 0,
                "assignment_level": "unassigned_no_candidates",
                "weight_method": None,
            }]))
            continue

        weight_sum = selected["weight"].sum()

        if weight_sum <= 0:
            allocation_parts.append(pd.DataFrame([{
                "source_taz": source_taz,
                "target_taz": None,
                "building_index": None,
                "gml_id": None,
                "category": category,
                "source_total": source_total,
                "weight": 0,
                "weight_sum": 0,
                "assigned_value": 0,
                "assignment_level": "unassigned_zero_weight",
                "weight_method": None,
            }]))
            continue

        selected["source_taz"] = source_taz
        selected["source_total"] = source_total
        selected["weight_sum"] = weight_sum
        selected["assigned_value"] = selected["weight"] / weight_sum * source_total
        selected["assignment_level"] = assignment_level

        allocation_parts.append(selected)

allocation_log = pd.concat(allocation_parts, ignore_index=True)

allocation_log.to_csv(ALLOCATION_LOG_CSV, index=False)

print("\nAllocation rows:", len(allocation_log))
print(allocation_log["assignment_level"].value_counts(dropna=False))

print("\nWorker allocation weight methods:")
print(
    allocation_log[allocation_log["category"] == WORKER_COL]["weight_method"]
    .value_counts(dropna=False)
)


# ============================================================
# 6. AGGREGATE ASSIGNED VALUES BACK TO BUILDING LEVEL
# ============================================================

valid_allocations = allocation_log[
    allocation_log["building_index"].notna()
].copy()

valid_allocations["building_index"] = valid_allocations["building_index"].astype(int)

assigned_wide = valid_allocations.pivot_table(
    index="building_index",
    columns="category",
    values="assigned_value",
    aggfunc="sum",
    fill_value=0
)

assigned_wide.columns = [f"assigned_{c}" for c in assigned_wide.columns]

result = buildings_taz.merge(
    assigned_wide,
    left_on="building_index",
    right_index=True,
    how="left"
)

for c in CATEGORY_COLS:
    col = f"assigned_{c}"
    if col not in result.columns:
        result[col] = 0

    result[col] = result[col].fillna(0)


# ============================================================
# 7. VALIDATION BY SOURCE TAZ
# ============================================================

validation = (
    allocation_log
    .groupby(["source_taz", "category"], dropna=False)["assigned_value"]
    .sum()
    .reset_index()
    .rename(columns={"assigned_value": "assigned_sum"})
)

source_totals_long = taz[[TAZ_ID_COL] + CATEGORY_COLS].melt(
    id_vars=TAZ_ID_COL,
    value_vars=CATEGORY_COLS,
    var_name="category",
    value_name="source_total"
).rename(columns={TAZ_ID_COL: "source_taz"})

validation = validation.merge(
    source_totals_long,
    on=["source_taz", "category"],
    how="right"
)

validation["assigned_sum"] = validation["assigned_sum"].fillna(0)

validation["source_total"] = pd.to_numeric(
    validation["source_total"],
    errors="coerce"
).fillna(0)

validation["difference"] = (
    validation["assigned_sum"] -
    validation["source_total"]
)

validation.to_csv(VALIDATION_CSV, index=False)

print("\nMaximum absolute difference by source TAZ/category:")
print(validation["difference"].abs().max())

print("\nUnassigned rows:")
print(
    allocation_log[
        allocation_log["assignment_level"].isin([
            "unassigned_no_candidates",
            "unassigned_zero_weight"
        ])
    ][[
        "source_taz",
        "category",
        "source_total",
        "assignment_level"
    ]]
)


# ============================================================
# 8. SAVE FINAL BUILDING OUTPUT
# ============================================================

result = gpd.GeoDataFrame(
    result,
    geometry="geometry",
    crs=taz.crs
)

result.to_file(
    OUTPUT_GPKG,
    driver="GPKG"
)

print("\nSaved:")
print(OUTPUT_GPKG)
print(VALIDATION_CSV)
print(ALLOCATION_LOG_CSV)

Strict worker caps:
arenas large events: 3790.08 m³
car dealerships: 3312.27 m³
customer service: 1586.94 m³
entertainment culture: 2099.76 m³
fitness wellness: 3163.88 m³
large cinemas: 7349.14 m³
large discos fun leisure pools: 3823.04 m³
restaurants gastronomy: 2847.13 m³
retail small scale: 1598.52 m³
theme parks: 37439.92 m³
vehicle electrical repair: 2527.98 m³

Large-format retail worker caps:
department stores: 60901.36 m³
discount stores: 13125.56 m³
diy stores: 70343.98 m³
factory outlet centers: 27929.44 m³
furniture stores: 84479.53 m³
hypermarkets superstores: 55123.86 m³
self service department stores: 9562.98 m³
shopping centers: 72152.44 m³

Candidate activity rows: 292361

Worker candidate weight methods:
weight_method
worker_potentials_original               237317
worker_strict_class_volume_capped_p75     12810
worker_large_format_volume_capped_p95       936
Name: count, dtype: int64

Allocation rows: 305414
assignment_level
within_taz                       273520
global_fallback                   21526
local_pool_same_plus_neighbor      7849
neighbor_taz                       2519
Name: count, dtype: int64

Worker allocation weight methods:
weight_method
worker_potentials_original               224614
worker_strict_class_volume_capped_p75     12379
worker_large_format_volume_capped_p95       933
Name: count, dtype: int64

Maximum absolute difference by source TAZ/category:
1.4551915228366852e-11

Unassigned rows:
Empty DataFrame
Columns: [source_taz, category, source_total, assignment_level]
Index: []

Saved:
Areas-of-interest-POIs/building_level_redistributed_values_with_fallback.gpkg
Areas-of-interest-POIs/redistribution_validation_with_fallback.csv
Areas-of-interest-POIs/redistribution_allocation_log.csv

In [19]:
# import pandas as pd
# import numpy as np

# # ---------------------------------------------------
# # Ensure volume is numeric
# # ---------------------------------------------------
# df["volume_m3"] = pd.to_numeric(
#     df["volume_m3"],
#     errors="coerce"
# )

# # ---------------------------------------------------
# # Normalize bosserhof_class
# # ---------------------------------------------------
# df["bosserhof_class_clean"] = (
#     df["bosserhof_class"]
#     .astype(str)
#     .str.lower()
#     .str.strip()
# )

# # ---------------------------------------------------
# # Filter restaurant / gastronomy buildings
# # ---------------------------------------------------
# restaurants = df[
#     df["bosserhof_class_clean"]
#     .str.contains("restaurant|gastronomy", na=False)
# ].copy()

# # Remove invalid volumes
# restaurants = restaurants[
#     restaurants["volume_m3"].notna() &
#     (restaurants["volume_m3"] > 0)
# ]

# # ---------------------------------------------------
# # Basic statistics
# # ---------------------------------------------------
# print(f"Restaurant buildings: {len(restaurants):,}")

# print("\n=== Volume Statistics (m³) ===")
# print(restaurants["volume_m3"].describe())

# # ---------------------------------------------------
# # Percentiles (important for cap selection)
# # ---------------------------------------------------
# percentiles = [0.50, 0.75, 0.90, 0.95, 0.99]

# print("\n=== Percentiles ===")
# print(
#     restaurants["volume_m3"]
#     .quantile(percentiles)
# )

# # ---------------------------------------------------
# # Largest restaurant-tagged buildings
# # ---------------------------------------------------
# largest = restaurants.sort_values(
#     "volume_m3",
#     ascending=False
# )[[
#     "gml_id",
#     "volume_m3",
#     "bosserhof_class",
#     "mid_label",
#     "osm_names",
# ]].head(20)

# print("\n=== Largest Restaurant Buildings ===")
# print(largest.to_string(index=False))

In [20]:
# # ============================================================
# # DIAGNOSTICS: PRINT WEIRD / SUSPICIOUS WORKER ASSIGNMENTS
# # ============================================================

# diagnostic = result.copy()

# diagnostic["volume_m3"] = pd.to_numeric(
#     diagnostic["volume_m3"],
#     errors="coerce"
# ).fillna(0)

# diagnostic["assigned_Workers"] = pd.to_numeric(
#     diagnostic["assigned_Workers"],
#     errors="coerce"
# ).fillna(0)

# diagnostic["potentials"] = pd.to_numeric(
#     diagnostic["potentials"],
#     errors="coerce"
# ).fillna(0)

# diagnostic["worker_per_1000m3"] = np.where(
#     diagnostic["volume_m3"] > 0,
#     diagnostic["assigned_Workers"] / diagnostic["volume_m3"] * 1000,
#     np.nan
# )

# diagnostic["worker_per_potential"] = np.where(
#     diagnostic["potentials"] > 0,
#     diagnostic["assigned_Workers"] / diagnostic["potentials"],
#     np.nan
# )

# HIGH_WORKER_Q = diagnostic["assigned_Workers"].quantile(0.99)
# HIGH_DENSITY_Q = diagnostic["worker_per_1000m3"].quantile(0.99)

# diagnostic["flag_high_workers"] = (
#     diagnostic["assigned_Workers"] >= HIGH_WORKER_Q
# )

# diagnostic["flag_high_worker_density"] = (
#     diagnostic["worker_per_1000m3"] >= HIGH_DENSITY_Q
# )

# diagnostic["flag_large_customer_facing_building"] = (
#     (diagnostic["assigned_Workers"] >= diagnostic["assigned_Workers"].quantile(0.95)) &
#     diagnostic["bosserhof_class_clean"].isin(
#         STRICT_WORKER_CAP_CLASSES + LARGE_FORMAT_RETAIL_CAP_CLASSES
#     )
# )

# diagnostic["worker_suspicion_score"] = (
#     diagnostic["flag_high_workers"].astype(int) +
#     diagnostic["flag_high_worker_density"].astype(int) +
#     diagnostic["flag_large_customer_facing_building"].astype(int)
# )

# suspicious_workers = diagnostic[
#     diagnostic["worker_suspicion_score"] > 0
# ].sort_values(
#     ["worker_suspicion_score", "assigned_Workers"],
#     ascending=False
# )

# cols = [
#     "gml_id",
#     "target_taz",
#     "assigned_Workers",
#     "volume_m3",
#     "potentials",
#     "worker_per_1000m3",
#     "worker_per_potential",
#     "bosserhof_class",
#     "bosserhof_class_clean",
#     "mid_label",
#     "osm_names",
#     "label_en",
#     "worker_suspicion_score",
#     "flag_high_workers",
#     "flag_high_worker_density",
#     "flag_large_customer_facing_building",
# ]

# cols = [c for c in cols if c in suspicious_workers.columns]

# print("\n============================================================")
# print("TOP SUSPICIOUS WORKER-ASSIGNED BUILDINGS")
# print("============================================================")
# print(f"99th percentile assigned_Workers: {HIGH_WORKER_Q:.2f}")
# print(f"99th percentile worker_per_1000m3: {HIGH_DENSITY_Q:.2f}")
# print(f"Suspicious buildings found: {len(suspicious_workers):,}")

# print(
#     suspicious_workers[cols]
#     .head(100)
#     .to_string(index=False)
# )


# # ============================================================
# # DIAGNOSTICS: BUILDINGS DOMINATING SOURCE TAZ WORKER ALLOCATION
# # ============================================================

# worker_alloc = allocation_log[
#     (allocation_log["category"] == WORKER_COL) &
#     (allocation_log["building_index"].notna())
# ].copy()

# worker_alloc["allocation_share_in_source_taz"] = np.where(
#     worker_alloc["source_total"] > 0,
#     worker_alloc["assigned_value"] / worker_alloc["source_total"],
#     np.nan
# )

# dominant_worker_alloc = worker_alloc[
#     worker_alloc["allocation_share_in_source_taz"] >= 0.35
# ].sort_values(
#     "allocation_share_in_source_taz",
#     ascending=False
# )

# dom_cols = [
#     "source_taz",
#     "target_taz",
#     "gml_id",
#     "assigned_value",
#     "source_total",
#     "allocation_share_in_source_taz",
#     "weight",
#     "weight_sum",
#     "assignment_level",
#     "weight_method",
#     "bosserhof_class",
#     "bosserhof_class_clean",
# ]

# dom_cols = [c for c in dom_cols if c in dominant_worker_alloc.columns]

# print("\n============================================================")
# print("BUILDINGS RECEIVING >=35% OF WORKERS FROM A SOURCE TAZ")
# print("============================================================")
# print(f"Dominant allocations found: {len(dominant_worker_alloc):,}")

# print(
#     dominant_worker_alloc[dom_cols]
#     .head(100)
#     .to_string(index=False)
# )


# # ============================================================
# # DIAGNOSTICS: RISKY WORKER FALLBACK ASSIGNMENTS
# # ============================================================

# risky_fallbacks = allocation_log[
#     (allocation_log["category"] == WORKER_COL) &
#     (allocation_log["assignment_level"].isin([
#         "neighbor_taz",
#         "global_fallback"
#     ]))
# ].copy()

# fallback_cols = [
#     "source_taz",
#     "target_taz",
#     "gml_id",
#     "assigned_value",
#     "source_total",
#     "assignment_level",
#     "weight_method",
#     "bosserhof_class",
#     "bosserhof_class_clean",
# ]

# fallback_cols = [c for c in fallback_cols if c in risky_fallbacks.columns]

# print("\n============================================================")
# print("WORKER ALLOCATIONS USING NEIGHBOR / GLOBAL FALLBACK")
# print("============================================================")
# print(f"Risky fallback allocations found: {len(risky_fallbacks):,}")

# print(
#     risky_fallbacks[fallback_cols]
#     .sort_values("assigned_value", ascending=False)
#     .head(100)
#     .to_string(index=False)
# )